# Generated by Django 2.0.8 on 2020-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteat', '0002_auto_20200821_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.CharField(choices=[('F', 'False'), ('C', 'Complete'), ('P', 'Pending')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='refCode',
            field=models.CharField(max_length=30, verbose_name='2MAWm0xi'),
        ),
    ]
