# Generated by Django 2.0.8 on 2020-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteat', '0003_auto_20200821_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
