# Generated by Django 2.0.8 on 2020-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasteat', '0004_auto_20200821_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(related_name='order_restaurants', to='fasteat.Restaurant'),
        ),
    ]
