# Generated by Django 2.0.8 on 2020-08-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasteat', '0007_auto_20200826_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='specification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
