# Generated by Django 2.0.8 on 2020-08-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasteat', '0008_auto_20200827_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='itemCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Food_category', to='fasteat.FoodCategory'),
        ),
    ]
