# Generated by Django 2.0.8 on 2020-08-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasteat', '0009_auto_20200828_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
