# Generated by Django 2.0.8 on 2020-08-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasteat', '0010_auto_20200829_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tableReference',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='size',
        ),
    ]
